GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "hei testi1", 
"author": "wt2fw",
"url": "http://localhost:3003/api/blogs", 
"likes": 234,
"userId": "65538b235ccca3e4424600a6"
}

